version: "3.7"

networks:
    codewithsravan-network:
      driver: bridge

services:
    nginx:
      container_name: nginx
      image: ${DOCKER_ACCT}/nginx
      build:
        context: .
        dockerfile: .docker/nginx.${APP_ENV}.dockerfile
      depends_on:
        - node
      ports: 
        - "80:80"
        - "443:443"
      networks: 
        - codewithsravan-network
    
    node:
      container_name: node-codewithsravan
      image: ${DOCKER_ACCT}/node-codewithsravan
      build:
        context: .
        dockerfile: .docker/node-codewithsravan.${APP_ENV}.dockerfile
      ports: 
        - "8080"
      volumes:
          - .:/var/www/codewithsravan
      working_dir: /var/www/codewithsravan
      env_file:
        - ./.docker/env/app.${APP_ENV}.env
      depends_on: 
        - mongo
        - redis
      networks:
        - codewithsravan-network
    
    mongo:
      container_name: mongo
      image: ${DOCKER_ACCT}/mongo
      build:
        context: .
        dockerfile: .docker/mongo.dockerfile
      ports:
      - "27017:27017"
      env_file:
        - ./.docker/env/mongo.${APP_ENV}.env
      networks:
        - codewithsravan-network
        
    redis:
      container_name: redis
      image: ${DOCKER_ACCT}/redis
      build: 
        context: .
        dockerfile: .docker/redis.${APP_ENV}.dockerfile
      ports:
        - "6379"
      networks:
        - codewithsravan-network


      
  

      

    
    
    
    
      
      